<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{BETYdb Tutorial}
%\VignetteEncoding{UTF-8}
-->



[BETYdb](https://www.betydb.org/) is the _Biofuel Ecophysiological Traits and Yields Database_. You can get many different types of data from this database, including trait data. 

Function setup: All functions are prefixed with `betydb_`. Plural function names like `betydb_traits()` accept parameters and always give back a data.frame, while singular function names like `betydb_trait()` accept an ID and give back a list.

The idea with the functions with plural names is to search for either traits, species, etc., and with the singular function names to get data by one or more IDs.

## Load traits


```r
library("traits")
```

## Traits

Get trait data for _Miscanthus giganteus_


```r
out <- betydb_search(query = "Switchgrass Yield")
```

Summarise data from the output `data.frame`


```r
library("dplyr")
out %>%
  group_by(id) %>%
  summarise(mean_result = mean(as.numeric(mean), na.rm = TRUE)) %>%
  arrange(desc(mean_result))
```

```
## Source: local data frame [509 x 2]
## 
##       id mean_result
## 1   1666       27.36
## 2  16845       27.00
## 3   1669       26.36
## 4  16518       26.00
## 5   1663       25.35
## 6  16742       25.00
## 7   1594       24.78
## 8   1674       22.71
## 9   1606       22.54
## 10  1665       22.46
## ..   ...         ...
```

Single trait


```r
betydb_trait(id = 10)
```

```
## $created_at
## NULL
## 
## $description
## [1] "Leaf Percent Nitrogen"
## 
## $id
## [1] 10
## 
## $label
## NULL
## 
## $max
## [1] "10"
## 
## $min
## [1] "0.02"
## 
## $name
## [1] "leafN"
## 
## $notes
## [1] ""
## 
## $standard_name
## NULL
## 
## $standard_units
## NULL
## 
## $units
## [1] "percent"
## 
## $updated_at
## [1] "2011-06-06T09:40:42-05:00"
```

## Species

Single species, _Acacia karroothorn_


```r
betydb_specie(id = 10)
```

```
## $AcceptedSymbol
## [1] "ACKA2"
## 
## $commonname
## [1] "karroothorn"
## 
## $created_at
## NULL
## 
## $genus
## [1] "Acacia"
## 
## $id
## [1] 10
## 
## $notes
## [1] ""
## 
## $scientificname
## [1] "Acacia karroo"
## 
## $spcd
## NULL
## 
## $species
## [1] "karroo"
## 
## $updated_at
## [1] "2011-03-01T15:02:25-06:00"
```

## Citations

Get citatons searching for _Miscanthus_


```r
betydb_citation(10)
```

```
## $author
## [1] "Casler"
## 
## $created_at
## NULL
## 
## $doi
## [1] "10.2135/cropsci2003.2226"
## 
## $id
## [1] 10
## 
## $journal
## [1] "Crop Science"
## 
## $pdf
## [1] "http://crop.scijournals.org/cgi/reprint/43/6/2226.pdf"
## 
## $pg
## [1] "2226–2233"
## 
## $title
## [1] "Cultivar X environment interactions in switchgrass"
## 
## $updated_at
## NULL
## 
## $url
## [1] "http://crop.scijournals.org/cgi/content/abstract/43/6/2226"
## 
## $user_id
## NULL
## 
## $vol
## [1] 43
## 
## $year
## [1] 2003
```

## Sites

Single site


```r
betydb_site(id = 1)
```

```
## $city
## [1] "Aliartos"
## 
## $country
## [1] "GR"
## 
## $geometry
## [1] "POINT (23.17 38.37 114.0)"
## 
## $greenhouse
## [1] FALSE
## 
## $notes
## [1] ""
## 
## $sitename
## [1] "Aliartos"
## 
## $state
## [1] ""
```

## Queries

For more detailed control over your search, use `betydb_query` to specify columns from any table of the database. If you don't specify a table, the yields and tables view (AKA the `/search` endpoint) is used by default.

```r
betydb_query(genus="Miscanthus")
```

```
## # A tibble: 6 × 36
##   access_level        author checked citation_id citation_year
##          <int>         <chr>   <int>       <int>         <int>
## 1            4 Clifton-Brown       1         189          2002
## 2            4 Clifton-Brown       1         189          2002
## 3            4 Clifton-Brown       1         189          2002
## 4            4 Clifton-Brown       1         189          2002
## 5            4 Clifton-Brown       1         189          2002
## 6            4 Clifton-Brown       1         189          2002
## # ... with 31 more variables: city <chr>, commonname <chr>,
## #   cultivar <chr>, cultivar_id <int>, date <chr>, dateloc <chr>,
## #   entity <lgl>, genus <chr>, id <int>, lat <dbl>, lon <dbl>,
## #   mean <dbl>, method_name <chr>, month <int>, n <int>,
## #   notes <chr>, raw_date <chr>, result_type <chr>,
## #   scientificname <chr>, site_id <int>, sitename <chr>,
## #   species_id <int>, stat <dbl>, statname <chr>, time <chr>,
## #   trait <chr>, trait_description <chr>, treatment <chr>,
## #   treatment_id <int>, units <chr>, year <int>
```

```r
betydb_query(genus="Miscanthus", table="species")
```

```
## # A tibble: 6 × 10
##   acceptedsymbol                 commonname
##            <chr>                      <chr>
## 1                                          
## 2           MISA           Amur silvergrass
## 3           MISI        Chinese silvergrass
## 4          MISCA                silvergrass
## 5         MICA16                silvergrass
## 6          MIFL3 Pacific Island silvergrass
## # ... with 8 more variables: created_at <chr>, genus <chr>,
## #   id <int>, notes <chr>, scientificname <chr>, spcd <lgl>,
## #   species <chr>, updated_at <chr>
```

```r
betydb_query(table = 'variables', name = 'Vcmax', betyurl = 'https://www.betydb.org//')
```

```
## # A tibble: 1 × 13
##   created_at                            description    id label
## *      <lgl>                                  <chr> <int> <lgl>
## 1         NA maximum rubisco carboxylation capacity     4    NA
## # ... with 9 more variables: max <chr>, min <chr>, name <chr>,
## #   notes <chr>, standard_name <lgl>, standard_units <lgl>,
## #   type <lgl>, units <chr>, updated_at <chr>
```

Each query term you provide restricts the one before it. This includes zero: passing no query terms will retrieve the whole table.

```r
betydb_query(table = 'citations')
```

```
## # A tibble: 814 × 13
##            author                created_at
## *           <chr>                     <chr>
## 1         Balasko                      <NA>
## 2           Price                      <NA>
## 3        Townsend 2016-04-11T17:24:35-05:00
## 4         Berdahl                      <NA>
## 5     Shiklomanov 2015-07-13T10:21:23-05:00
## 6       Baldocchi 2016-07-12T12:36:53-05:00
## 7  Liu, Changming 2016-07-12T12:44:22-05:00
## 8      Clegg, Max 2016-07-12T12:49:42-05:00
## 9          Wertin 2016-07-12T17:18:39-05:00
## 10       Missaoui                      <NA>
## # ... with 804 more rows, and 11 more variables: doi <chr>,
## #   id <dbl>, journal <chr>, pdf <chr>, pg <chr>, title <chr>,
## #   updated_at <chr>, url <chr>, user_id <dbl>, vol <int>,
## #   year <int>
```

```r
betydb_query(table = 'citations', author = 'Aasamaa')
```
```
## # A tibble: 2 × 13
##    author                created_at
## *   <chr>                     <chr>
## 1 Aasamaa 2011-07-13T14:46:00-05:00
## 2 Aasamaa 2010-09-02T13:44:07-05:00
## # ... with 11 more variables: doi <chr>, id <int>, journal <chr>,
## #   pdf <chr>, pg <chr>, title <chr>, updated_at <chr>,
## #   url <chr>, user_id <int>, vol <int>, year <int>
```

```r
betydb_query(table = 'citations', author = 'Aasamaa', year="2010")
```

```
## # A tibble: 1 × 13
##    author                created_at
## *   <chr>                     <chr>
## 1 Aasamaa 2011-07-13T14:46:00-05:00
## # ... with 11 more variables: doi <chr>, id <int>, journal <chr>,
## #   pdf <chr>, pg <chr>, title <chr>, updated_at <chr>,
## #   url <chr>, user_id <int>, vol <int>, year <int>
```

Passing an ID should only ever match one result. Note that this is similar, but not identical, to the single-item view from the matching singular bety_<tablename> function. For example, compare `bety_citation(id=1)` and `betydb_query(id = 1, table = 'citations')`. 

If using the new API, regular expression search works...

```r
betydb_query(distn= "~norm", table = 'priors', api_version="beta")
```

```
## # A tibble: 116 × 15
##       id citation_id variable_id  phylogeny distn parama paramb
## *  <int>       <int>       <int>      <chr> <chr>  <dbl>  <dbl>
## 1     40          51           4            lnorm  4.510  0.640
## 2    287         838         568      grass lnorm  0.180  0.430
## 3    288         840         492 Miscanthus lnorm -2.300  0.550
## 4     10         203          22   C3 grass lnorm  1.240  0.900
## 5     48         195          39   C4 crops  norm  0.057  0.006
## 6     69          NA          26            lnorm  1.760  0.380
## 7     49         195          39        CAM  norm  0.033  0.020
## 8     75          NA          21            lnorm  0.210  0.600
## 9     90         276          37   C4 grass  norm 10.000  5.000
## 10    20         277          26            lnorm  2.300  1.000
## # ... with 106 more rows, and 8 more variables: paramc <dbl>,
## #   n <int>, notes <chr>, created_at <chr>, updated_at <chr>,
## #   `number of associated pfts` <int>, view_url <chr>,
## #   edit_url <chr>
```

...including, perversely but sometimes usefully, regular expressions treating numeric values as if they were strings!

```r
betydb_query(parama = "~0.0", table = 'priors', api_version="beta")
```

```
## # A tibble: 34 × 15
##       id citation_id variable_id        phylogeny distn parama
## *  <int>       <int>       <int>            <chr> <chr>  <dbl>
## 1     48         195          39         C4 crops  norm 0.0570
## 2     49         195          39              CAM  norm 0.0330
## 3    171         223         198             tree  unif 0.0010
## 4    238         561          46            trees  unif 0.0200
## 5    240         561         500            trees  unif 0.0100
## 6    241         561         501            trees  unif 0.0100
## 7    242         561         502            trees  unif 0.0100
## 8    243         561         503            trees  unif 0.0100
## 9    131         223          40        evergreen  unif 0.0400
## 10   146         439         195 tundra evergreen  norm 0.0004
## # ... with 24 more rows, and 9 more variables: paramb <dbl>,
## #   paramc <lgl>, n <int>, notes <chr>, created_at <chr>,
## #   updated_at <chr>, `number of associated pfts` <int>,
## #   view_url <chr>, edit_url <chr>
```

## Changing which results you see

There are three special query terms that can limit which matching rows are returned: `limit`, `offset`, and `include_unchecked`.

### limit and offset

These parameters apply to the beta API only. The v0 API always returns all rows that match your query. This can be slow for large result sets, so newer API versions provide control over the number of rows retrieved at a time. By default, the API will return no more than 200 results when `limit` is unset. If you're sure you want all results in one request, use `limit = "none"`.

```r
options(betydb_api_version="beta")

sla <- betydb_search("Maple SLA")
# Warning message:
# In betydb_GET(url, args = list(...), key = key, user = NULL, pwd = NULL,  :
#  The 40370-row result set exceeds the default 200 row limit.  Showing the first 200 results only.  Set an explicit limit to show more results.

sla2 <- betydb_search("Maple SLA", limit=300)
sla3 <- betydb_search("Maple SLA", limit=100, offset=200)
identical(sla2$id, c(sla$id, sla3$id))
# [1] TRUE
```

### include_unchecked

By default, BETY only shows results that have been checked for quality by an administrator. However, the tables `search`, `traits`, and `yields` contain many observations that are not checked but may still be of scientific interest. To query all values, add  `include_unchecked="true"` to your query, then sort or filter the unchecked values as you see fit by using the flags in the `checked` column of the result.

```r
misc_dur_checked <- betydb_query(table="search", genus="Miscanthus", sitename="Durmersheim")
misc_dur_checked %>% group_by(year) %>% summarize(n())
# # A tibble: 3 × 2
#    year `n()`
#   <int> <int>
# 1  1994     4
# 2  1995    24
# 3    NA     2

misc_dur_all <- betydb_query(table="search", genus="Miscanthus", sitename="Durmersheim", include_unchecked=TRUE)
misc_dur_all %>% group_by(year, checked) %>% summarize(n())
# Source: local data frame [6 x 3]
# Groups: year [?]
#
#    year checked `n()`
#   <int>   <int> <int>
# 1  1994       0     5
# 2  1994       1     4
# 3  1995       0    12
# 4  1995       1    24
# 5  1996       0     2
# 6    NA       1     2
```

You can also query the `checked` column directly. This is possible even without `include_unchecked`, though in that case the result is predictable:

```r
betydb_search("Miscanthus Durmersheim", checked=0)
# NULL
betydb_search("Miscanthus Durmersheim", checked=0, include_unchecked=TRUE)
# # A tibble: 19 × 36
#    access_level      author checked citation_id citation_year
# *         <int>       <chr>   <int>       <int>         <int>
# 1             4 Lewandowski       0         158          1997
# 2             4 Lewandowski       0         158          1997
# 3             4 Lewandowski       0         158          1997
# 4             4 Lewandowski       0         158          1997
# 5             4 Lewandowski       0         158          1997
# ...
```
